<?php
// database/seeders/ExerciseDatabaseSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ExerciseDatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // Get category IDs
        $categories = DB::table('exercise_caragories')
            ->pluck('catagory_id', 'catagory_name');

        // Default user ID (change this if needed)
        $userId = 1;

        $exercises = [
            // Cardiovascular Exercises
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Running'],
                'exercise_name' => 'Treadmill Running',
                'exercise_type' => 'cardiovascular',
                'calories_per_minute' => 11.5,
                'description' => 'Running on a treadmill at moderate pace',
                'instructions' => 'Start with a warm-up walk for 5 minutes, then run at a pace where you can maintain a conversation for 20-30 minutes, cool down with a 5-minute walk.',
                'muscle_groups' => json_encode(['Quadriceps', 'Hamstrings', 'Glutes', 'Calves', 'Core']),
                'equipment_needed' => 'Treadmill',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Running'],
                'exercise_name' => 'Interval Sprints',
                'exercise_type' => 'cardiovascular',
                'calories_per_minute' => 14.8,
                'description' => 'High-intensity interval running',
                'instructions' => 'After warm-up, sprint at maximum effort for 30 seconds, then walk or jog for 60 seconds. Repeat 8-12 times.',
                'muscle_groups' => json_encode(['Quadriceps', 'Hamstrings', 'Glutes', 'Calves', 'Core']),
                'equipment_needed' => 'None',
                'difficulty_level' => 'advanced',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Cycling'],
                'exercise_name' => 'Stationary Bike',
                'exercise_type' => 'cardiovascular',
                'calories_per_minute' => 8.5,
                'description' => 'Moderate intensity stationary cycling',
                'instructions' => 'Adjust seat height so your knee is slightly bent at the bottom of the pedal stroke. Maintain a steady pace of 60-80 RPM for 20-45 minutes.',
                'muscle_groups' => json_encode(['Quadriceps', 'Hamstrings', 'Glutes', 'Calves']),
                'equipment_needed' => 'Stationary Bike',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Swimming'],
                'exercise_name' => 'Freestyle Swimming',
                'exercise_type' => 'cardiovascular',
                'calories_per_minute' => 10.8,
                'description' => 'Continuous freestyle swimming laps',
                'instructions' => 'Swim freestyle continuously for 20-30 minutes, focusing on proper form and breathing technique.',
                'muscle_groups' => json_encode(['Shoulders', 'Back', 'Chest', 'Core', 'Legs']),
                'equipment_needed' => 'Swimming Pool',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['HIIT Cardio'],
                'exercise_name' => 'HIIT Circuit',
                'exercise_type' => 'cardiovascular',
                'calories_per_minute' => 13.5,
                'description' => 'High-intensity interval training circuit',
                'instructions' => 'Perform each exercise for 45 seconds with 15 seconds rest: jumping jacks, burpees, mountain climbers, high knees. Repeat circuit 4-5 times.',
                'muscle_groups' => json_encode(['Full Body']),
                'equipment_needed' => 'None',
                'difficulty_level' => 'advanced',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Jump Rope'],
                'exercise_name' => 'Basic Jump Rope',
                'exercise_type' => 'cardiovascular',
                'calories_per_minute' => 12.3,
                'description' => 'Continuous jumping with a rope',
                'instructions' => 'Jump continuously for 1-5 minute intervals with 30-second rest periods. Maintain good posture and land softly.',
                'muscle_groups' => json_encode(['Calves', 'Quadriceps', 'Shoulders', 'Core']),
                'equipment_needed' => 'Jump Rope',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Rowing'],
                'exercise_name' => 'Rowing Machine',
                'exercise_type' => 'cardiovascular',
                'calories_per_minute' => 10.5,
                'description' => 'Indoor rowing machine workout',
                'instructions' => 'Maintain proper form: push with legs, lean back slightly, pull arms to chest. Row for 20-30 minutes at steady pace.',
                'muscle_groups' => json_encode(['Legs', 'Back', 'Shoulders', 'Arms', 'Core']),
                'equipment_needed' => 'Rowing Machine',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Elliptical'],
                'exercise_name' => 'Elliptical Trainer',
                'exercise_type' => 'cardiovascular',
                'calories_per_minute' => 9.2,
                'description' => 'Low-impact cardio on elliptical machine',
                'instructions' => 'Maintain an upright posture and use both forward and reverse motions. Exercise for 20-45 minutes.',
                'muscle_groups' => json_encode(['Quadriceps', 'Hamstrings', 'Glutes', 'Calves']),
                'equipment_needed' => 'Elliptical Machine',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Stair Climbing'],
                'exercise_name' => 'Stair Climber',
                'exercise_type' => 'cardiovascular',
                'calories_per_minute' => 11.0,
                'description' => 'Stair climbing machine workout',
                'instructions' => 'Maintain an upright posture and avoid leaning on the handrails. Climb for 20-30 minutes.',
                'muscle_groups' => json_encode(['Quadriceps', 'Glutes', 'Calves', 'Core']),
                'equipment_needed' => 'Stair Climber Machine',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Hiking'],
                'exercise_name' => 'Trail Hiking',
                'exercise_type' => 'cardiovascular',
                'calories_per_minute' => 8.0,
                'description' => 'Hiking on natural trails',
                'instructions' => 'Wear appropriate footwear and carry water. Hike on varied terrain for 45-90 minutes.',
                'muscle_groups' => json_encode(['Quadriceps', 'Hamstrings', 'Glutes', 'Calves', 'Core']),
                'equipment_needed' => 'Hiking Boots, Backpack',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Dancing'],
                'exercise_name' => 'Zumba',
                'exercise_type' => 'cardiovascular',
                'calories_per_minute' => 8.5,
                'description' => 'Dance-based fitness class',
                'instructions' => 'Follow along with Zumba routines, focusing on fun movement rather than perfection. Participate for 45-60 minutes.',
                'muscle_groups' => json_encode(['Full Body']),
                'equipment_needed' => 'None',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Kickboxing'],
                'exercise_name' => 'Cardio Kickboxing',
                'exercise_type' => 'cardiovascular',
                'calories_per_minute' => 10.2,
                'description' => 'Kickboxing-inspired cardio workout',
                'instructions' => 'Perform combinations of punches, kicks, and knee strikes in continuous motion for 45-60 minutes.',
                'muscle_groups' => json_encode(['Legs', 'Core', 'Shoulders', 'Arms']),
                'equipment_needed' => 'None (or gloves and bag for advanced)',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Stair Running'],
                'exercise_name' => 'Stadium Stairs',
                'exercise_type' => 'cardiovascular',
                'calories_per_minute' => 13.5,
                'description' => 'Running up and down stadium stairs',
                'instructions' => 'Run up stairs at a brisk pace, walk or jog down. Repeat for 20-30 minutes.',
                'muscle_groups' => json_encode(['Quadriceps', 'Glutes', 'Calves', 'Core']),
                'equipment_needed' => 'Stairs',
                'difficulty_level' => 'advanced',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Circuit Training'],
                'exercise_name' => 'Cardio Circuit',
                'exercise_type' => 'cardiovascular',
                'calories_per_minute' => 11.8,
                'description' => 'Circuit training with cardio focus',
                'instructions' => 'Perform each exercise for 45 seconds with 15 seconds rest: jumping jacks, burpees, mountain climbers, high knees, skater jumps. Repeat circuit 4-5 times.',
                'muscle_groups' => json_encode(['Full Body']),
                'equipment_needed' => 'None',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Cross Trainer'],
                'exercise_name' => 'Cross Trainer Intervals',
                'exercise_type' => 'cardiovascular',
                'calories_per_minute' => 10.0,
                'description' => 'Interval training on cross trainer',
                'instructions' => 'Alternate between 2 minutes at moderate pace and 1 minute at high intensity for 20-30 minutes.',
                'muscle_groups' => json_encode(['Quadriceps', 'Hamstrings', 'Glutes', 'Calves', 'Arms']),
                'equipment_needed' => 'Cross Trainer Machine',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Step Aerobics'],
                'exercise_name' => 'Step Aerobics',
                'exercise_type' => 'cardiovascular',
                'calories_per_minute' => 9.5,
                'description' => 'Choreographed step aerobics routine',
                'instructions' => 'Follow along with step aerobics routine, maintaining proper form and height on the step. Exercise for 45-60 minutes.',
                'muscle_groups' => json_encode(['Quadriceps', 'Glutes', 'Calves', 'Core']),
                'equipment_needed' => 'Step Platform',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],

            // Strength Exercises - Chest
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Chest Exercises'],
                'exercise_name' => 'Barbell Bench Press',
                'exercise_type' => 'strength',
                'calories_per_minute' => 5.2,
                'description' => 'Flat bench press using a barbell',
                'instructions' => 'Lie on flat bench with feet flat on floor. Grip barbell slightly wider than shoulder width. Lower bar to chest, then press back up to starting position.',
                'muscle_groups' => json_encode(['Pectoralis Major', 'Anterior Deltoids', 'Triceps']),
                'equipment_needed' => 'Barbell, Bench',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Chest Exercises'],
                'exercise_name' => 'Dumbbell Flyes',
                'exercise_type' => 'strength',
                'calories_per_minute' => 4.5,
                'description' => 'Chest isolation exercise with dumbbells',
                'instructions' => 'Lie on flat bench with dumbbells extended above chest. Lower weights out to sides with slight bend in elbows, then return to starting position.',
                'muscle_groups' => json_encode(['Pectoralis Major']),
                'equipment_needed' => 'Dumbbells, Bench',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Chest Exercises'],
                'exercise_name' => 'Incline Bench Press',
                'exercise_type' => 'strength',
                'calories_per_minute' => 5.5,
                'description' => 'Bench press on an inclined bench',
                'instructions' => 'Lie on incline bench with feet flat on floor. Grip barbell slightly wider than shoulder width. Lower bar to upper chest, then press back up.',
                'muscle_groups' => json_encode(['Upper Pectorals', 'Anterior Deltoids', 'Triceps']),
                'equipment_needed' => 'Barbell, Incline Bench',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Chest Exercises'],
                'exercise_name' => 'Push-Ups',
                'exercise_type' => 'strength',
                'calories_per_minute' => 6.2,
                'description' => 'Bodyweight chest exercise',
                'instructions' => 'Place hands slightly wider than shoulder width. Keep body in straight line from head to heels. Lower chest to floor, then push back up.',
                'muscle_groups' => json_encode(['Pectorals', 'Triceps', 'Core']),
                'equipment_needed' => 'None',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Chest Exercises'],
                'exercise_name' => 'Cable Crossovers',
                'exercise_type' => 'strength',
                'calories_per_minute' => 4.8,
                'description' => 'Cable machine chest exercise',
                'instructions' => 'Set pulleys at high position. Stand in center, grab handles, and bring hands together in front of body in arc motion.',
                'muscle_groups' => json_encode(['Pectorals']),
                'equipment_needed' => 'Cable Machine',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],

            // Strength Exercises - Back
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Back Exercises'],
                'exercise_name' => 'Pull-Ups',
                'exercise_type' => 'strength',
                'calories_per_minute' => 6.8,
                'description' => 'Bodyweight pulling exercise',
                'instructions' => 'Grip pull-up bar with hands slightly wider than shoulder width. Pull yourself up until your chin clears the bar, then lower with control.',
                'muscle_groups' => json_encode(['Latissimus Dorsi', 'Biceps', 'Rhomboids']),
                'equipment_needed' => 'Pull-Up Bar',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Back Exercises'],
                'exercise_name' => 'Bent-Over Rows',
                'exercise_type' => 'strength',
                'calories_per_minute' => 5.5,
                'description' => 'Rowing motion with bent torso',
                'instructions' => 'Stand with feet shoulder-width apart, knees slightly bent. Bend at hips until torso is nearly parallel to floor. Pull barbell to lower chest, then lower with control.',
                'muscle_groups' => json_encode(['Latissimus Dorsi', 'Rhomboids', 'Trapezius']),
                'equipment_needed' => 'Barbell',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Back Exercises'],
                'exercise_name' => 'Lat Pulldowns',
                'exercise_type' => 'strength',
                'calories_per_minute' => 5.0,
                'description' => 'Machine exercise targeting lats',
                'instructions' => 'Sit at lat pulldown machine with thighs secured under pads. Grip bar wider than shoulder width. Pull bar down to upper chest, then return with control.',
                'muscle_groups' => json_encode(['Latissimus Dorsi', 'Biceps']),
                'equipment_needed' => 'Lat Pulldown Machine',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Back Exercises'],
                'exercise_name' => 'Seated Cable Rows',
                'exercise_type' => 'strength',
                'calories_per_minute' => 5.2,
                'description' => 'Rowing exercise using cable machine',
                'instructions' => 'Sit at cable row machine with feet braced. Grab handle with neutral grip. Pull handle to abdomen while keeping back straight, then return with control.',
                'muscle_groups' => json_encode(['Rhomboids', 'Latissimus Dorsi', 'Middle Back']),
                'equipment_needed' => 'Cable Machine',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Back Exercises'],
                'exercise_name' => 'Deadlift',
                'exercise_type' => 'strength',
                'calories_per_minute' => 7.5,
                'description' => 'Lift weight from ground to standing position',
                'instructions' => 'Stand with feet hip-width apart, barbell over mid-foot. Bend at hips and knees to grip bar. Keep back straight as you stand up with the weight, then lower with control.',
                'muscle_groups' => json_encode(['Erector Spinae', 'Glutes', 'Hamstrings', 'Lats']),
                'equipment_needed' => 'Barbell',
                'difficulty_level' => 'advanced',
                'is_verified' => true,
                'is_public' => true,
            ],

            // Strength Exercises - Shoulders
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Shoulder Exercises'],
                'exercise_name' => 'Overhead Press',
                'exercise_type' => 'strength',
                'calories_per_minute' => 5.0,
                'description' => 'Press weight overhead from shoulders',
                'instructions' => 'Stand or sit with barbell at shoulder height. Press bar overhead until arms are fully extended, then lower with control.',
                'muscle_groups' => json_encode(['Deltoids', 'Triceps', 'Upper Chest']),
                'equipment_needed' => 'Barbell',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Shoulder Exercises'],
                'exercise_name' => 'Dumbbell Lateral Raises',
                'exercise_type' => 'strength',
                'calories_per_minute' => 4.2,
                'description' => 'Isolation exercise for medial deltoids',
                'instructions' => 'Stand with dumbbells at sides. With slight bend in elbows, raise weights out to sides until arms are parallel to floor, then lower with control.',
                'muscle_groups' => json_encode(['Medial Deltoids']),
                'equipment_needed' => 'Dumbbells',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Shoulder Exercises'],
                'exercise_name' => 'Front Raises',
                'exercise_type' => 'strength',
                'calories_per_minute' => 4.0,
                'description' => 'Isolation exercise for anterior deltoids',
                'instructions' => 'Stand with dumbbells in front of thighs. Raise weights forward until arms are parallel to floor, then lower with control.',
                'muscle_groups' => json_encode(['Anterior Deltoids']),
                'equipment_needed' => 'Dumbbells',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Shoulder Exercises'],
                'exercise_name' => 'Upright Rows',
                'exercise_type' => 'strength',
                'calories_per_minute' => 5.2,
                'description' => 'Vertical pulling exercise for shoulders',
                'instructions' => 'Stand with barbell or dumbbells in front of thighs. Pull weights upward close to body until they reach chin level, then lower with control.',
                'muscle_groups' => json_encode(['Deltoids', 'Trapezius']),
                'equipment_needed' => 'Barbell or Dumbbells',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Shoulder Exercises'],
                'exercise_name' => 'Face Pulls',
                'exercise_type' => 'strength',
                'calories_per_minute' => 4.5,
                'description' => 'Exercise for rear deltoids and upper back',
                'instructions' => 'Set cable pulley at face height. Grab rope attachment with overhand grip. Pull rope towards face while separating hands, squeezing shoulder blades together.',
                'muscle_groups' => json_encode(['Posterior Deltoids', 'Rhomboids']),
                'equipment_needed' => 'Cable Machine',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],

            // Strength Exercises - Legs
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Leg Exercises'],
                'exercise_name' => 'Barbell Squats',
                'exercise_type' => 'strength',
                'calories_per_minute' => 7.5,
                'description' => 'Compound lower body exercise',
                'instructions' => 'Place barbell across upper back. Keep chest up and back straight. Lower until thighs are parallel to floor, then drive through heels to return to standing.',
                'muscle_groups' => json_encode(['Quadriceps', 'Glutes', 'Hamstrings', 'Core']),
                'equipment_needed' => 'Barbell',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Leg Exercises'],
                'exercise_name' => 'Dumbbell Lunges',
                'exercise_type' => 'strength',
                'calories_per_minute' => 6.8,
                'description' => 'Unilateral leg exercise',
                'instructions' => 'Stand with dumbbells at sides. Step forward with one leg, lowering until both knees are bent 90 degrees. Push back to starting position.',
                'muscle_groups' => json_encode(['Quadriceps', 'Glutes', 'Hamstrings']),
                'equipment_needed' => 'Dumbbells',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Leg Exercises'],
                'exercise_name' => 'Leg Press',
                'exercise_type' => 'strength',
                'calories_per_minute' => 6.5,
                'description' => 'Machine-based leg exercise',
                'instructions' => 'Sit on leg press machine with feet shoulder-width apart on platform. Push platform away until legs are extended, then return to starting position.',
                'muscle_groups' => json_encode(['Quadriceps', 'Glutes', 'Hamstrings']),
                'equipment_needed' => 'Leg Press Machine',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Quadriceps Exercises'],
                'exercise_name' => 'Leg Extensions',
                'exercise_type' => 'strength',
                'calories_per_minute' => 4.5,
                'description' => 'Isolation exercise for quadriceps',
                'instructions' => 'Sit on leg extension machine with ankles behind pad. Extend legs until they are straight, then lower with control.',
                'muscle_groups' => json_encode(['Quadriceps']),
                'equipment_needed' => 'Leg Extension Machine',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Hamstring Exercises'],
                'exercise_name' => 'Hamstring Curls',
                'exercise_type' => 'strength',
                'calories_per_minute' => 4.5,
                'description' => 'Isolation exercise for hamstrings',
                'instructions' => 'Lie face down on leg curl machine with ankles under pad. Curl legs up toward glutes, then lower with control.',
                'muscle_groups' => json_encode(['Hamstrings']),
                'equipment_needed' => 'Leg Curl Machine',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Glute Exercises'],
                'exercise_name' => 'Hip Thrusts',
                'exercise_type' => 'strength',
                'calories_per_minute' => 5.5,
                'description' => 'Exercise targeting glute muscles',
                'instructions' => 'Sit on floor with upper back against bench, barbell across hips. Drive through heels to lift hips until body forms straight line from shoulders to knees.',
                'muscle_groups' => json_encode(['Glutes', 'Hamstrings']),
                'equipment_needed' => 'Barbell, Bench',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Calf Exercises'],
                'exercise_name' => 'Standing Calf Raises',
                'exercise_type' => 'strength',
                'calories_per_minute' => 3.8,
                'description' => 'Exercise for calf muscles',
                'instructions' => 'Stand on edge of step or platform with heels hanging off. Raise up on toes as high as possible, then lower heels below step level.',
                'muscle_groups' => json_encode(['Calves']),
                'equipment_needed' => 'Step or Platform',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Leg Exercises'],
                'exercise_name' => 'Bulgarian Split Squats',
                'exercise_type' => 'strength',
                'calories_per_minute' => 6.2,
                'description' => 'Single-leg squat variation',
                'instructions' => 'Stand lunge-length in front of bench. Place top of back foot on bench. Lower until front thigh is parallel to floor, then drive back up.',
                'muscle_groups' => json_encode(['Quadriceps', 'Glutes', 'Hamstrings']),
                'equipment_needed' => 'Bench, Dumbbells (optional)',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Leg Exercises'],
                'exercise_name' => 'Romanian Deadlifts',
                'exercise_type' => 'strength',
                'calories_per_minute' => 6.0,
                'description' => 'Hip hinge exercise for posterior chain',
                'instructions' => 'Stand with barbell or dumbbells. With slight bend in knees, hinge at hips to lower weight toward floor while keeping back straight. Return to standing.',
                'muscle_groups' => json_encode(['Hamstrings', 'Glutes', 'Lower Back']),
                'equipment_needed' => 'Barbell or Dumbbells',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Leg Exercises'],
                'exercise_name' => 'Box Jumps',
                'exercise_type' => 'strength',
                'calories_per_minute' => 9.2,
                'description' => 'Plyometric leg exercise',
                'instructions' => 'Stand facing box with feet shoulder-width apart. Swing arms and jump onto box, landing softly with knees bent. Step down and repeat.',
                'muscle_groups' => json_encode(['Quadriceps', 'Glutes', 'Calves', 'Core']),
                'equipment_needed' => 'Plyometric Box',
                'difficulty_level' => 'advanced',
                'is_verified' => true,
                'is_public' => true,
            ],

            // Strength Exercises - Arms
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Bicep Exercises'],
                'exercise_name' => 'Barbell Curls',
                'exercise_type' => 'strength',
                'calories_per_minute' => 4.0,
                'description' => 'Basic bicep exercise with barbell',
                'instructions' => 'Stand with barbell at waist, palms facing forward. Curl weight up toward shoulders, then lower with control.',
                'muscle_groups' => json_encode(['Biceps']),
                'equipment_needed' => 'Barbell',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Bicep Exercises'],
                'exercise_name' => 'Dumbbell Hammer Curls',
                'exercise_type' => 'strength',
                'calories_per_minute' => 4.2,
                'description' => 'Bicep exercise with neutral grip',
                'instructions' => 'Stand with dumbbells at sides, palms facing each other. Curl weights up toward shoulders, then lower with control.',
                'muscle_groups' => json_encode(['Biceps', 'Brachialis']),
                'equipment_needed' => 'Dumbbells',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Bicep Exercises'],
                'exercise_name' => 'Preacher Curls',
                'exercise_type' => 'strength',
                'calories_per_minute' => 4.3,
                'description' => 'Isolation bicep exercise',
                'instructions' => 'Sit at preacher curl bench with arms resting on pad. Curl weight up, then lower with control.',
                'muscle_groups' => json_encode(['Biceps']),
                'equipment_needed' => 'Preacher Curl Bench, Barbell or Dumbbells',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Tricep Exercises'],
                'exercise_name' => 'Tricep Pushdowns',
                'exercise_type' => 'strength',
                'calories_per_minute' => 4.2,
                'description' => 'Cable exercise for triceps',
                'instructions' => 'Stand at cable machine with rope or bar attachment. Keeping elbows at sides, push weight down until arms are extended, then return with control.',
                'muscle_groups' => json_encode(['Triceps']),
                'equipment_needed' => 'Cable Machine',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Tricep Exercises'],
                'exercise_name' => 'Overhead Tricep Extension',
                'exercise_type' => 'strength',
                'calories_per_minute' => 4.5,
                'description' => 'Exercise for long head of triceps',
                'instructions' => 'Sit or stand with dumbbell held overhead with both hands. Lower weight behind head, then extend arms to return to starting position.',
                'muscle_groups' => json_encode(['Triceps']),
                'equipment_needed' => 'Dumbbell',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Tricep Exercises'],
                'exercise_name' => 'Close-Grip Bench Press',
                'exercise_type' => 'strength',
                'calories_per_minute' => 5.8,
                'description' => 'Compound tricep exercise',
                'instructions' => 'Lie on bench with hands closer than shoulder width. Lower bar to chest, then press back up, focusing on tricep engagement.',
                'muscle_groups' => json_encode(['Triceps', 'Chest', 'Shoulders']),
                'equipment_needed' => 'Barbell, Bench',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Forearm Exercises'],
                'exercise_name' => 'Wrist Curls',
                'exercise_type' => 'strength',
                'calories_per_minute' => 3.5,
                'description' => 'Exercise for forearm flexors',
                'instructions' => 'Sit on bench with forearms resting on thighs, wrists hanging off knees. Curl weight up with wrists, then lower with control.',
                'muscle_groups' => json_encode(['Forearms']),
                'equipment_needed' => 'Dumbbell or Barbell',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Forearm Exercises'],
                'exercise_name' => 'Reverse Wrist Curls',
                'exercise_type' => 'strength',
                'calories_per_minute' => 3.5,
                'description' => 'Exercise for forearm extensors',
                'instructions' => 'Sit on bench with forearms resting on thighs, palms facing down. Extend wrists upward, then lower with control.',
                'muscle_groups' => json_encode(['Forearms']),
                'equipment_needed' => 'Dumbbell or Barbell',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],

            // Strength Exercises - Core
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Core Exercises'],
                'exercise_name' => 'Plank',
                'exercise_type' => 'strength',
                'calories_per_minute' => 3.2,
                'description' => 'Isometric core exercise',
                'instructions' => 'Assume push-up position but with weight on forearms. Keep body in straight line from head to heels. Hold for 30-60 seconds.',
                'muscle_groups' => json_encode(['Rectus Abdominis', 'Transverse Abdominis', 'Obliques']),
                'equipment_needed' => 'None',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Core Exercises'],
                'exercise_name' => 'Russian Twists',
                'exercise_type' => 'strength',
                'calories_per_minute' => 4.5,
                'description' => 'Rotational core exercise',
                'instructions' => 'Sit on floor with knees bent, leaning back slightly. Hold weight with both hands and twist torso from side to side.',
                'muscle_groups' => json_encode(['Obliques', 'Rectus Abdominis']),
                'equipment_needed' => 'Dumbbell or Medicine Ball',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Abdominal Exercises'],
                'exercise_name' => 'Crunches',
                'exercise_type' => 'strength',
                'calories_per_minute' => 3.8,
                'description' => 'Basic abdominal exercise',
                'instructions' => 'Lie on back with knees bent, feet flat on floor. Place hands behind head and curl upper body toward knees, then lower with control.',
                'muscle_groups' => json_encode(['Rectus Abdominis']),
                'equipment_needed' => 'None',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Abdominal Exercises'],
                'exercise_name' => 'Leg Raises',
                'exercise_type' => 'strength',
                'calories_per_minute' => 4.2,
                'description' => 'Lower abdominal exercise',
                'instructions' => 'Lie on back with legs straight. Keeping legs straight, raise them until perpendicular to floor, then lower with control.',
                'muscle_groups' => json_encode(['Lower Abs', 'Hip Flexors']),
                'equipment_needed' => 'None',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Oblique Exercises'],
                'exercise_name' => 'Side Plank',
                'exercise_type' => 'strength',
                'calories_per_minute' => 3.5,
                'description' => 'Isometric oblique exercise',
                'instructions' => 'Lie on side with legs straight. Prop up on forearm with elbow under shoulder. Lift hips to form straight line from head to feet. Hold for 30-60 seconds.',
                'muscle_groups' => json_encode(['Obliques', 'Transverse Abdominis']),
                'equipment_needed' => 'None',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Core Exercises'],
                'exercise_name' => 'Hanging Leg Raises',
                'exercise_type' => 'strength',
                'calories_per_minute' => 5.2,
                'description' => 'Advanced core exercise',
                'instructions' => 'Hang from pull-up bar with arms straight. Raise legs until they are parallel to floor, then lower with control.',
                'muscle_groups' => json_encode(['Lower Abs', 'Hip Flexors', 'Obliques']),
                'equipment_needed' => 'Pull-Up Bar',
                'difficulty_level' => 'advanced',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Core Exercises'],
                'exercise_name' => 'Ab Wheel Rollouts',
                'exercise_type' => 'strength',
                'calories_per_minute' => 5.5,
                'description' => 'Advanced core stability exercise',
                'instructions' => 'Kneel on floor holding ab wheel. Roll forward until body is extended, then use core to roll back to starting position.',
                'muscle_groups' => json_encode(['Rectus Abdominis', 'Obliques', 'Transverse Abdominis']),
                'equipment_needed' => 'Ab Wheel',
                'difficulty_level' => 'advanced',
                'is_verified' => true,
                'is_public' => true,
            ],

            // Flexibility Exercises
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Static Stretching'],
                'exercise_name' => 'Hamstring Stretch',
                'exercise_type' => 'flexibility',
                'calories_per_minute' => 1.8,
                'description' => 'Seated hamstring stretch',
                'instructions' => 'Sit on floor with one leg extended and the other bent. Lean forward toward extended leg until you feel a stretch. Hold for 30 seconds.',
                'muscle_groups' => json_encode(['Hamstrings', 'Calves']),
                'equipment_needed' => 'None',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Static Stretching'],
                'exercise_name' => 'Quadriceps Stretch',
                'exercise_type' => 'flexibility',
                'calories_per_minute' => 1.5,
                'description' => 'Standing quad stretch',
                'instructions' => 'Stand and hold onto support if needed. Bend one knee and grasp ankle, pulling heel toward glute until you feel a stretch. Hold for 30 seconds.',
                'muscle_groups' => json_encode(['Quadriceps']),
                'equipment_needed' => 'None',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Yoga'],
                'exercise_name' => 'Downward-Facing Dog',
                'exercise_type' => 'flexibility',
                'calories_per_minute' => 2.5,
                'description' => 'Fundamental yoga pose',
                'instructions' => 'Start on hands and knees. Lift hips toward ceiling, forming an inverted V shape. Keep hands shoulder-width and feet hip-width apart. Hold for 5-10 breaths.',
                'muscle_groups' => json_encode(['Hamstrings', 'Calves', 'Shoulders', 'Back']),
                'equipment_needed' => 'Yoga Mat',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Yoga'],
                'exercise_name' => 'Warrior II',
                'exercise_type' => 'flexibility',
                'calories_per_minute' => 2.8,
                'description' => 'Standing yoga pose',
                'instructions' => 'Stand with feet wide apart. Turn right foot out 90 degrees, left foot slightly in. Bend right knee over ankle, extending arms parallel to floor. Hold for 5-10 breaths.',
                'muscle_groups' => json_encode(['Quadriceps', 'Hip Flexors', 'Shoulders']),
                'equipment_needed' => 'Yoga Mat',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Pilates'],
                'exercise_name' => 'The Hundred',
                'exercise_type' => 'flexibility',
                'calories_per_minute' => 3.2,
                'description' => 'Classic Pilates breathing exercise',
                'instructions' => 'Lie on back with legs in tabletop position. Lift head and shoulders off mat. Pump arms up and down while breathing in for 5 counts and out for 5 counts. Repeat for 100 pumps.',
                'muscle_groups' => json_encode(['Rectus Abdominis', 'Transverse Abdominis']),
                'equipment_needed' => 'Pilates Mat',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Dynamic Stretching'],
                'exercise_name' => 'Leg Swings',
                'exercise_type' => 'flexibility',
                'calories_per_minute' => 3.0,
                'description' => 'Dynamic hip mobility exercise',
                'instructions' => 'Stand holding onto support. Swing one leg forward and backward in controlled motion. Repeat 10-15 times per leg.',
                'muscle_groups' => json_encode(['Hip Flexors', 'Hamstrings', 'Glutes']),
                'equipment_needed' => 'None',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],

            // Sports Exercises
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Basketball'],
                'exercise_name' => 'Layup Drills',
                'exercise_type' => 'sports',
                'calories_per_minute' => 8.2,
                'description' => 'Basketball layup practice',
                'instructions' => 'Practice layups from both sides of the basket. Focus on proper footwork and shooting technique. Repeat 10-20 times from each side.',
                'muscle_groups' => json_encode(['Quadriceps', 'Glutes', 'Calves', 'Core']),
                'equipment_needed' => 'Basketball, Hoop',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Basketball'],
                'exercise_name' => 'Free Throw Practice',
                'exercise_type' => 'sports',
                'calories_per_minute' => 4.5,
                'description' => 'Basketball free throw shooting practice',
                'instructions' => 'Practice free throw shooting with proper form and routine. Shoot 50-100 free throws focusing on consistency.',
                'muscle_groups' => json_encode(['Shoulders', 'Arms', 'Core']),
                'equipment_needed' => 'Basketball, Hoop',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Soccer'],
                'exercise_name' => 'Dribbling Drills',
                'exercise_type' => 'sports',
                'calories_per_minute' => 7.8,
                'description' => 'Soccer ball control practice',
                'instructions' => 'Set up cone course and practice dribbling through it with both feet. Focus on close ball control and changes of direction.',
                'muscle_groups' => json_encode(['Legs', 'Core', 'Coordination']),
                'equipment_needed' => 'Soccer Ball, Cones',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Soccer'],
                'exercise_name' => 'Shooting Practice',
                'exercise_type' => 'sports',
                'calories_per_minute' => 8.5,
                'description' => 'Soccer shooting technique practice',
                'instructions' => 'Practice shooting on goal from various distances and angles. Focus on proper technique and accuracy.',
                'muscle_groups' => json_encode(['Legs', 'Core', 'Coordination']),
                'equipment_needed' => 'Soccer Ball, Goal',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Tennis'],
                'exercise_name' => 'Forehand Drills',
                'exercise_type' => 'sports',
                'calories_per_minute' => 7.5,
                'description' => 'Tennis forehand stroke practice',
                'instructions' => 'Practice forehand strokes with a partner or ball machine. Focus on proper form, footwork, and follow-through.',
                'muscle_groups' => json_encode(['Shoulders', 'Core', 'Legs']),
                'equipment_needed' => 'Tennis Racket, Tennis Balls',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Boxing'],
                'exercise_name' => 'Heavy Bag Work',
                'exercise_type' => 'sports',
                'calories_per_minute' => 10.5,
                'description' => 'Punching combination practice on heavy bag',
                'instructions' => 'Practice various punch combinations on heavy bag. Focus on proper form, power, and speed. 3-minute rounds with 1-minute rest.',
                'muscle_groups' => json_encode(['Shoulders', 'Chest', 'Back', 'Core']),
                'equipment_needed' => 'Boxing Gloves, Heavy Bag',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],

            // Other Exercises
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Plyometrics'],
                'exercise_name' => 'Box Jumps',
                'exercise_type' => 'other',
                'calories_per_minute' => 9.2,
                'description' => 'Explosive jumping onto box',
                'instructions' => 'Stand facing box with feet shoulder-width apart. Swing arms and jump onto box, landing softly with knees bent. Step down and repeat.',
                'muscle_groups' => json_encode(['Quadriceps', 'Glutes', 'Calves', 'Core']),
                'equipment_needed' => 'Plyometric Box',
                'difficulty_level' => 'advanced',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Balance Training'],
                'exercise_name' => 'Single-Leg Stand',
                'exercise_type' => 'other',
                'calories_per_minute' => 2.1,
                'description' => 'Balance exercise on one leg',
                'instructions' => 'Stand on one leg with slight bend in knee. Maintain balance for 30-60 seconds. Progress by closing eyes or standing on unstable surface.',
                'muscle_groups' => json_encode(['Ankle Stabilizers', 'Core', 'Hip Stabilizers']),
                'equipment_needed' => 'None',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Calisthenics'],
                'exercise_name' => 'Muscle-Ups',
                'exercise_type' => 'other',
                'calories_per_minute' => 8.5,
                'description' => 'Advanced bodyweight exercise combining pull-up and dip',
                'instructions' => 'From a dead hang, explosively pull yourself up and over the bar, transitioning into a dip at the top. Lower with control.',
                'muscle_groups' => json_encode(['Back', 'Chest', 'Shoulders', 'Arms']),
                'equipment_needed' => 'Pull-Up Bar',
                'difficulty_level' => 'advanced',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Kettlebell'],
                'exercise_name' => 'Kettlebell Swings',
                'exercise_type' => 'other',
                'calories_per_minute' => 8.8,
                'description' => 'Explosive hip hinge exercise with kettlebell',
                'instructions' => 'Stand with feet shoulder-width apart, kettlebell on floor. Hinge at hips to grab kettlebell. Swing it to chest height using hip power, not arms.',
                'muscle_groups' => json_encode(['Glutes', 'Hamstrings', 'Core', 'Shoulders']),
                'equipment_needed' => 'Kettlebell',
                'difficulty_level' => 'intermediate',
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'created_by_user_id' => $userId,
                'catagory_id' => $categories['Resistance Band'],
                'exercise_name' => 'Band Pull-Aparts',
                'exercise_type' => 'other',
                'calories_per_minute' => 3.5,
                'description' => 'Shoulder health exercise with resistance band',
                'instructions' => 'Hold resistance band with both hands, arms straight. Pull band apart by squeezing shoulder blades together. Return with control.',
                'muscle_groups' => json_encode(['Rear Deltoids', 'Rhomboids']),
                'equipment_needed' => 'Resistance Band',
                'difficulty_level' => 'beginner',
                'is_verified' => true,
                'is_public' => true,
            ],
        ];

        foreach ($exercises as $exercise) {
            DB::table('exercise_databases')->insert(array_merge($exercise, [
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]));
        }
    }
}