<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FoodItemsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('food_items')->insert([
            // 🍳 Breakfast Foods (1)
            ['food_name' => 'Firfir', 'category_id' => 1,'serving_size' => '1 plate', 'serving_unit' => 'plate', 'calories_per_serving' => 400, 'protein_per_serving' => 10, 'carbs_per_serving' => 50, 'fat_per_serving' => 15, 'fiber_per_serving' => 5, 'sugar_per_serving' => 2, 'sodium_per_serving' => 200, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Genfo', 'category_id' => 1, 'serving_size' => '1 bowl', 'serving_unit' => 'bowl', 'calories_per_serving' => 250, 'protein_per_serving' => 7, 'carbs_per_serving' => 45, 'fat_per_serving' => 5, 'fiber_per_serving' => 4, 'sugar_per_serving' => 2, 'sodium_per_serving' => 30, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Kita', 'category_id' => 1, 'serving_size' => '1 piece', 'serving_unit' => 'piece', 'calories_per_serving' => 180, 'protein_per_serving' => 5, 'carbs_per_serving' => 35, 'fat_per_serving' => 1.5, 'fiber_per_serving' => 4, 'sugar_per_serving' => 1, 'sodium_per_serving' => 15, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Ambasha', 'category_id' => 1, 'serving_size' => '1 slice', 'serving_unit' => 'slice', 'calories_per_serving' => 200, 'protein_per_serving' => 6, 'carbs_per_serving' => 40, 'fat_per_serving' => 2, 'fiber_per_serving' => 3, 'sugar_per_serving' => 5, 'sodium_per_serving' => 20, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Egg Firfir', 'category_id' => 1, 'serving_size' => '1 plate', 'serving_unit' => 'plate', 'calories_per_serving' => 320, 'protein_per_serving' => 14, 'carbs_per_serving' => 20, 'fat_per_serving' => 18, 'fiber_per_serving' => 2, 'sugar_per_serving' => 2, 'sodium_per_serving' => 220, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Chechebsa', 'category_id' => 1, 'serving_size' => '1 plate', 'serving_unit' => 'plate', 'calories_per_serving' => 400, 'protein_per_serving' => 10, 'carbs_per_serving' => 45, 'fat_per_serving' => 20, 'fiber_per_serving' => 5, 'sugar_per_serving' => 3, 'sodium_per_serving' => 250, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Milk (Fresh)', 'category_id' => 1, 'serving_size' => '1 cup', 'serving_unit' => 'cup', 'calories_per_serving' => 150, 'protein_per_serving' => 8, 'carbs_per_serving' => 12, 'fat_per_serving' => 8, 'fiber_per_serving' => 0, 'sugar_per_serving' => 12, 'sodium_per_serving' => 120, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Buna (Coffee)', 'category_id' => 1, 'serving_size' => '1 cup', 'serving_unit' => 'cup', 'calories_per_serving' => 5, 'protein_per_serving' => 0, 'carbs_per_serving' => 1, 'fat_per_serving' => 0, 'fiber_per_serving' => 0, 'sugar_per_serving' => 0, 'sodium_per_serving' => 1, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],

            // 🍲 Lunch & Dinner (2)
            ['food_name' => 'Injera', 'category_id' => 2, 'serving_size' => '1 piece', 'serving_unit' => 'piece', 'calories_per_serving' => 120, 'protein_per_serving' => 4, 'carbs_per_serving' => 25, 'fat_per_serving' => 0.7, 'fiber_per_serving' => 3, 'sugar_per_serving' => 1, 'sodium_per_serving' => 10, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Shiro Wot', 'category_id' => 2, 'serving_size' => '1 cup', 'serving_unit' => 'cup', 'calories_per_serving' => 350, 'protein_per_serving' => 12, 'carbs_per_serving' => 30, 'fat_per_serving' => 15, 'fiber_per_serving' => 8, 'sugar_per_serving' => 5, 'sodium_per_serving' => 500, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Doro Wot', 'category_id' => 2, 'serving_size' => '1 plate', 'serving_unit' => 'plate', 'calories_per_serving' => 500, 'protein_per_serving' => 28, 'carbs_per_serving' => 20, 'fat_per_serving' => 30, 'fiber_per_serving' => 3, 'sugar_per_serving' => 3, 'sodium_per_serving' => 700, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Kitfo', 'category_id' => 2, 'serving_size' => '1 plate', 'serving_unit' => 'plate', 'calories_per_serving' => 600, 'protein_per_serving' => 35, 'carbs_per_serving' => 5, 'fat_per_serving' => 50, 'fiber_per_serving' => 0, 'sugar_per_serving' => 0, 'sodium_per_serving' => 400, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Tibs', 'category_id' => 2, 'serving_size' => '1 plate', 'serving_unit' => 'plate', 'calories_per_serving' => 450, 'protein_per_serving' => 30, 'carbs_per_serving' => 10, 'fat_per_serving' => 25, 'fiber_per_serving' => 2, 'sugar_per_serving' => 1, 'sodium_per_serving' => 350, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Dulet', 'category_id' => 2, 'serving_size' => '1 plate', 'serving_unit' => 'plate', 'calories_per_serving' => 480, 'protein_per_serving' => 28, 'carbs_per_serving' => 10, 'fat_per_serving' => 40, 'fiber_per_serving' => 2, 'sugar_per_serving' => 1, 'sodium_per_serving' => 500, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Rice (Boiled)', 'category_id' => 2, 'serving_size' => '1 cup', 'serving_unit' => 'cup', 'calories_per_serving' => 200, 'protein_per_serving' => 4, 'carbs_per_serving' => 45, 'fat_per_serving' => 0.5, 'fiber_per_serving' => 2, 'sugar_per_serving' => 0, 'sodium_per_serving' => 2, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Pasta (Plain)', 'category_id' => 2, 'serving_size' => '1 cup', 'serving_unit' => 'cup', 'calories_per_serving' => 220, 'protein_per_serving' => 7, 'carbs_per_serving' => 43, 'fat_per_serving' => 1, 'fiber_per_serving' => 2, 'sugar_per_serving' => 1, 'sodium_per_serving' => 5, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Kocho', 'category_id' => 2, 'serving_size' => '1 slice', 'serving_unit' => 'slice', 'calories_per_serving' => 150, 'protein_per_serving' => 2, 'carbs_per_serving' => 35, 'fat_per_serving' => 0.5, 'fiber_per_serving' => 3, 'sugar_per_serving' => 1, 'sodium_per_serving' => 4, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Misir Wot', 'category_id' => 2, 'serving_size' => '1 cup', 'serving_unit' => 'cup', 'calories_per_serving' => 280, 'protein_per_serving' => 18, 'carbs_per_serving' => 35, 'fat_per_serving' => 6, 'fiber_per_serving' => 12, 'sugar_per_serving' => 3, 'sodium_per_serving' => 400, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Suf fitfit', 'category_id' => 2, 'serving_size' => '1 cup', 'serving_unit' => 'cup', 'calories_per_serving' => 300, 'protein_per_serving' => 15, 'carbs_per_serving' => 40, 'fat_per_serving' => 8, 'fiber_per_serving' => 10, 'sugar_per_serving' => 2, 'sodium_per_serving' => 350, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Ayib', 'category_id' => 2, 'serving_size' => '1/2 cup', 'serving_unit' => 'cup', 'calories_per_serving' => 100, 'protein_per_serving' => 11, 'carbs_per_serving' => 3, 'fat_per_serving' => 5, 'fiber_per_serving' => 0, 'sugar_per_serving' => 3, 'sodium_per_serving' => 50, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],

            // 🥗 Vegetables & Salads (3)
            ['food_name' => 'Gomen', 'category_id' => 3, 'serving_size' => '1 cup', 'serving_unit' => 'cup', 'calories_per_serving' => 80, 'protein_per_serving' => 4, 'carbs_per_serving' => 10, 'fat_per_serving' => 2, 'fiber_per_serving' => 5, 'sugar_per_serving' => 2, 'sodium_per_serving' => 60, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Atkilt', 'category_id' => 3, 'serving_size' => '1 cup', 'serving_unit' => 'cup', 'calories_per_serving' => 120, 'protein_per_serving' => 3, 'carbs_per_serving' => 20, 'fat_per_serving' => 4, 'fiber_per_serving' => 5, 'sugar_per_serving' => 3, 'sodium_per_serving' => 70, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Fosolia', 'category_id' => 3, 'serving_size' => '1 cup', 'serving_unit' => 'cup', 'calories_per_serving' => 90, 'protein_per_serving' => 3, 'carbs_per_serving' => 15, 'fat_per_serving' => 3, 'fiber_per_serving' => 4, 'sugar_per_serving' => 2, 'sodium_per_serving' => 50, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Beetroot Salad', 'category_id' => 3, 'serving_size' => '1 cup', 'serving_unit' => 'cup', 'calories_per_serving' => 60, 'protein_per_serving' => 2, 'carbs_per_serving' => 13, 'fat_per_serving' => 0.2, 'fiber_per_serving' => 4, 'sugar_per_serving' => 9, 'sodium_per_serving' => 70, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Tomato Salad', 'category_id' => 3, 'serving_size' => '1 cup', 'serving_unit' => 'cup', 'calories_per_serving' => 30, 'protein_per_serving' => 1, 'carbs_per_serving' => 6, 'fat_per_serving' => 0.2, 'fiber_per_serving' => 2, 'sugar_per_serving' => 4, 'sodium_per_serving' => 20, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],

            // 🍌 Fruits (4)
            ['food_name' => 'Banana', 'category_id' => 4, 'serving_size' => '1 medium', 'serving_unit' => 'piece', 'calories_per_serving' => 105, 'protein_per_serving' => 1, 'carbs_per_serving' => 27, 'fat_per_serving' => 0.3, 'fiber_per_serving' => 3, 'sugar_per_serving' => 14, 'sodium_per_serving' => 1, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Avocado', 'category_id' => 4, 'serving_size' => '1 medium', 'serving_unit' => 'piece', 'calories_per_serving' => 250, 'protein_per_serving' => 3, 'carbs_per_serving' => 12, 'fat_per_serving' => 23, 'fiber_per_serving' => 10, 'sugar_per_serving' => 1, 'sodium_per_serving' => 10, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Mango', 'category_id' => 4, 'serving_size' => '1 medium', 'serving_unit' => 'piece', 'calories_per_serving' => 200, 'protein_per_serving' => 2, 'carbs_per_serving' => 50, 'fat_per_serving' => 1, 'fiber_per_serving' => 5, 'sugar_per_serving' => 45, 'sodium_per_serving' => 5, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Papaya', 'category_id' => 4, 'serving_size' => '1 cup', 'serving_unit' => 'cup', 'calories_per_serving' => 120, 'protein_per_serving' => 2, 'carbs_per_serving' => 30, 'fat_per_serving' => 0.5, 'fiber_per_serving' => 3, 'sugar_per_serving' => 20, 'sodium_per_serving' => 4, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Orange', 'category_id' => 4, 'serving_size' => '1 medium', 'serving_unit' => 'piece', 'calories_per_serving' => 62, 'protein_per_serving' => 1, 'carbs_per_serving' => 15, 'fat_per_serving' => 0.2, 'fiber_per_serving' => 3, 'sugar_per_serving' => 12, 'sodium_per_serving' => 0, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Apple', 'category_id' => 4, 'serving_size' => '1 medium', 'serving_unit' => 'piece', 'calories_per_serving' => 92, 'protein_per_serving' => 1, 'carbs_per_serving' => 25, 'fat_per_serving' => 0.3, 'fiber_per_serving' => 3, 'sugar_per_serving' => 12, 'sodium_per_serving' => 0, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Watermelon', 'category_id' => 4, 'serving_size' => '1 cup', 'serving_unit' => 'cup', 'calories_per_serving' => 46, 'protein_per_serving' => 1, 'carbs_per_serving' => 12, 'fat_per_serving' => 0.2, 'fiber_per_serving' => 1, 'sugar_per_serving' => 9, 'sodium_per_serving' => 1, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Pineapple', 'category_id' => 4, 'serving_size' => '1 cup', 'serving_unit' => 'cup', 'calories_per_serving' => 120, 'protein_per_serving' => 2, 'carbs_per_serving' => 30, 'fat_per_serving' => 0.5, 'fiber_per_serving' => 3, 'sugar_per_serving' => 20, 'sodium_per_serving' => 4, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],

            // 🍪 Snacks & Street Foods (5)
            ['food_name' => 'Kolo', 'category_id' => 5, 'serving_size' => '1 handful', 'serving_unit' => 'handful', 'calories_per_serving' => 150, 'protein_per_serving' => 5, 'carbs_per_serving' => 30, 'fat_per_serving' => 2, 'fiber_per_serving' => 4, 'sugar_per_serving' => 1, 'sodium_per_serving' => 20, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Beso', 'category_id' => 5, 'serving_size' => '1 cup', 'serving_unit' => 'cup', 'calories_per_serving' => 250, 'protein_per_serving' => 8, 'carbs_per_serving' => 45, 'fat_per_serving' => 5, 'fiber_per_serving' => 6, 'sugar_per_serving' => 2, 'sodium_per_serving' => 30, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Sambusa', 'category_id' => 5, 'serving_size' => '1 piece', 'serving_unit' => 'piece', 'calories_per_serving' => 180, 'protein_per_serving' => 6, 'carbs_per_serving' => 20, 'fat_per_serving' => 8, 'fiber_per_serving' => 2, 'sugar_per_serving' => 1, 'sodium_per_serving' => 180, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Potato Fries', 'category_id' => 5, 'serving_size' => '1 plate', 'serving_unit' => 'plate', 'calories_per_serving' => 300, 'protein_per_serving' => 5, 'carbs_per_serving' => 40, 'fat_per_serving' => 15, 'fiber_per_serving' => 4, 'sugar_per_serving' => 1, 'sodium_per_serving' => 350, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Baklava', 'category_id' => 6, 'serving_size' => '1 piece', 'serving_unit' => 'piece', 'calories_per_serving' => 200, 'protein_per_serving' => 3, 'carbs_per_serving' => 25, 'fat_per_serving' => 10, 'fiber_per_serving' => 1, 'sugar_per_serving' => 15, 'sodium_per_serving' => 100, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Chocolate Cake', 'category_id' => 6, 'serving_size' => '1 slice', 'serving_unit' => 'slice', 'calories_per_serving' => 350, 'protein_per_serving' => 5, 'carbs_per_serving' => 45, 'fat_per_serving' => 15, 'fiber_per_serving' => 2, 'sugar_per_serving' => 30, 'sodium_per_serving' => 150, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
            ['food_name' => 'Ice Cream', 'category_id' => 6, 'serving_size' => '1 cup', 'serving_unit' => 'cup', 'calories_per_serving' => 250, 'protein_per_serving' => 4, 'carbs_per_serving' => 30, 'fat_per_serving' => 12, 'fiber_per_serving' => 1, 'sugar_per_serving' => 20, 'sodium_per_serving' => 80, 'is_verified' => true, 'is_public' => true, 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
